gpg_agent: |
  enable-ssh-support
  grab
  default-cache-ttl 10800
  default-cache-ttl-ssh 10800
  allow-emacs-pinentry
  allow-loopback-pinentry
  # log-file /tmp/gpg-agent.log
  # debug-level advanced
gpg: |
  cert-digest-algo SHA512
  charset utf-8
  default-preference-list SHA512 SHA384 SHA256 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed
  fixed-list-mode
  keyid-format 0xlong
  list-options show-uid-validity
  no-comments
  no-emit-version
  no-symkey-cache
  personal-cipher-preferences AES256 AES192 AES
  personal-compress-preferences ZLIB BZIP2 ZIP Uncompressed
  personal-digest-preferences SHA512 SHA384 SHA256
  require-cross-certification
  s2k-cipher-algo AES256
  s2k-digest-algo SHA512
  use-agent
  verify-options show-uid-validity
  with-fingerprint
scdaemon: |
  disable-ccid
