card_reset:
  args:
    - "--card-edit"
    - "--pinentry-mode"
    - "loopback"
    - "--command-fd=0"
    - "--status-fd=1"
    - "--no-tty"
  interactions:
    - pattern: "cardedit.prompt"
      response: "admin"
    - pattern: "cardedit.prompt"
      response: "factory-reset"
    - pattern: "cardedit.factory-reset.proceed"
      response: "yes"
    - pattern: "cardedit.factory-reset.really"
      response: "yes"
    - pattern: "cardedit.prompt"
      response: "quit"

card_set_keyattrs:
  args:
    - "--card-edit"
    - "--pinentry-mode"
    - "loopback"
    - "--command-fd=0"
    - "--status-fd=1"
    - "--no-tty"
  interactions:
    - pattern: "cardedit.prompt"
      response: "admin"
    - pattern: "cardedit.prompt"
      response: "key-attr"
    - pattern: "cardedit.genkeys.algo"
      response: "2"
    - pattern: "keygen.curve"
      response: "1"
    - pattern: "passphrase.enter"
      response: "12345678"
    - pattern: "cardedit.genkeys.algo"
      response: "2"
    - pattern: "keygen.curve"
      response: "1"
    - pattern: "passphrase.enter"
      response: "12345678"
    - pattern: "cardedit.genkeys.algo"
      response: "2"
    - pattern: "keygen.curve"
      response: "1"
    - pattern: "passphrase.enter"
      response: "12345678"
    - pattern: "cardedit.prompt"
      response: "quit"

card_set_owner:
  args:
    - "--card-edit"
    - "--pinentry-mode"
    - "loopback"
    - "--command-fd=0"
    - "--status-fd=1"
    - "--no-tty"
  interactions:
    - pattern: "cardedit.prompt"
      response: "admin"
    - pattern: "cardedit.prompt"
      response: "name"
    - pattern: "keygen.smartcard.surname"
      response: "LastName"
    - pattern: "keygen.smartcard.givenname"
      response: "FirstName"
    - pattern: "passphrase.enter"
      response: "12345678"
    - pattern: "cardedit.prompt"
      response: "login"
    - pattern: "cardedit.change_login"
      response: "email@address.com"
    - pattern: "cardedit.prompt"
      response: "lang"
    - pattern: "cardedit.change_lang"
      response: "en"
    - pattern: "cardedit.prompt"
      response: "salutation"
    - pattern: "cardedit.change_sex"
      response: "m"
    - pattern: "cardedit.prompt"
      response: "quit"

key_revcert:
  args:
    - "--pinentry-mode"
    - "loopback"
    - "--command-fd=0"
    - "--status-fd=1"
    - "--no-tty"

  interactions:
    - pattern: "gen_revoke.okay"
      response: "y"
    - pattern: "ask_revocation_reason.code"
      response: "0"
    - pattern: "ask_revocation_reason.text"
      response: "\n"
    - pattern: "ask_revocation_reason.okay"
      response: "y"

key_keytocard:
  args:
    - "--edit-key"
    - "--pinentry-mode"
    - "loopback"
    - "--command-fd=0"
    - "--status-fd=1"
    - "--no-tty"

  interactions:
    - pattern: "keyedit.prompt"
      response: "key"
    - pattern: "keyedit.prompt"
      response: "key 1"
    - pattern: "keyedit.prompt"
      response: "keytocard"
    - pattern: "cardedit.genkeys.storekeytype"
      response: "2"
      meta: "e"

    # - pattern: "passphrase.enter"
    #   response: "12345678"

    - pattern: "keyedit.prompt"
      response: "key"
    - pattern: "keyedit.prompt"
      response: "key 2"
    - pattern: "keyedit.prompt"
      response: "keytocard"
    - pattern: "cardedit.genkeys.storekeytype"
      response: "1"
      meta: "s"

    - pattern: "keyedit.prompt"
      response: "key"
    - pattern: "keyedit.prompt"
      response: "key 3"
    - pattern: "keyedit.prompt"
      response: "keytocard"
    - pattern: "cardedit.genkeys.storekeytype"
      response: "3"
      meta: "a"

    - pattern: "keyedit.prompt"
      response: "save"
