bip39key:
  args:
    - "--format"
    - "pgp"
    - "--seed-format"
    - "bip39"
    - "--authorization-for-sign-key"
    - "--generate-sign-subkey"
    - "--generate-auth-key"

user:
  first_name: "Test"
  last_name: "Testing User"
  email: "somewhere@cool.io"
  # mnemonic: "sight long verb dawn purpose poverty afford fitness leave pear talent grow over menu enemy sail climb coil glow banana grow until find tissue"
