labels:
- color: '#CC0000'
  description: An issue with the system 🐛.
  name: bug
- color: '#336699'
  description: New functionality.
  name: feature
repository:
  allow_merge_commit: true
  allow_rebase_merge: false
  allow_squash_merge: true
  default_branch: master
  delete_branch_on_merge: true
  description: (BIP39 mnemonic) Generate and/or Dump to OpenPGP card an ed25519 key
  has_downloads: true
  has_issues: true
  has_projects: false
  has_wiki: false
  name: dkeygen
  private: false
