# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bip39key = {
    pname = "bip39key";
    version = "4e14c1c29d2ca20cbddc4df53fc378f4d9c98797";
    src = fetchgit {
      url = "https://github.com/voobscout/bip39key";
      rev = "4e14c1c29d2ca20cbddc4df53fc378f4d9c98797";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-41p+FF3LlntHAXqF+12zxVVXVZdEzIOMef55CbUY3pY=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./bip39key-4e14c1c29d2ca20cbddc4df53fc378f4d9c98797/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-05-30";
  };
  crystal2nix = {
    pname = "crystal2nix";
    version = "1d2357653ed79cd5d0d231ef88b9f4943c5b6ec1";
    src = fetchgit {
      url = "https://github.com/voobscout/crystal2nix";
      rev = "1d2357653ed79cd5d0d231ef88b9f4943c5b6ec1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+fMxexyIGEoXEFr3E6DWLzaA3VeaOfCgA+Wu1ovvQ00=";
    };
    date = "2025-06-22";
  };
  crystalline = {
    pname = "crystalline";
    version = "v0.17.1";
    src = fetchFromGitHub {
      owner = "elbywan";
      repo = "crystalline";
      rev = "v0.17.1";
      fetchSubmodules = false;
      sha256 = "sha256-SIfInDY6KhEwEPZckgobOrpKXBDDd0KhQt/IjdGBhWo=";
    };
  };
}
